onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /Block1_vlg_tst/eachvec
add wave -noupdate /Block1_vlg_tst/treg_dm_inout
add wave -noupdate /Block1_vlg_tst/treg_dp_inout
add wave -noupdate /Block1_vlg_tst/inclk
add wave -noupdate /Block1_vlg_tst/RX_COM1
add wave -noupdate /Block1_vlg_tst/RX_COM2
add wave -noupdate /Block1_vlg_tst/clk_usb
add wave -noupdate /Block1_vlg_tst/d_out_enable
add wave -noupdate /Block1_vlg_tst/dm_inout
add wave -noupdate /Block1_vlg_tst/dp_inout
add wave -noupdate /Block1_vlg_tst/tx_clk
add wave -noupdate /Block1_vlg_tst/TX_COM1
add wave -noupdate /Block1_vlg_tst/TX_COM2
add wave -noupdate /Block1_vlg_tst/TX_COM_LED1
add wave -noupdate /Block1_vlg_tst/TX_COM_LED2
add wave -noupdate /Block1_vlg_tst/ones_cnt
add wave -noupdate /Block1_vlg_tst/ls_pause/num_bits
add wave -noupdate /Block1_vlg_tst/send_ls_byte/sbyte
add wave -noupdate /Block1_vlg_tst/send_ls_byte/i
add wave -noupdate /Block1_vlg_tst/i1/inclk
add wave -noupdate /Block1_vlg_tst/i1/RX_COM1
add wave -noupdate /Block1_vlg_tst/i1/RX_COM2
add wave -noupdate /Block1_vlg_tst/i1/tx_clk
add wave -noupdate /Block1_vlg_tst/i1/TX_COM1
add wave -noupdate /Block1_vlg_tst/i1/TX_COM2
add wave -noupdate /Block1_vlg_tst/i1/d_out_enable
add wave -noupdate /Block1_vlg_tst/i1/TX_COM_LED1
add wave -noupdate /Block1_vlg_tst/i1/TX_COM_LED2
add wave -noupdate /Block1_vlg_tst/i1/dp_inout
add wave -noupdate /Block1_vlg_tst/i1/dm_inout
add wave -noupdate /Block1_vlg_tst/i1/b2v_inst/clk
add wave -noupdate /Block1_vlg_tst/i1/b2v_inst/dp
add wave -noupdate /Block1_vlg_tst/i1/b2v_inst/dm
add wave -noupdate /Block1_vlg_tst/i1/b2v_inst/d_out_enable
add wave -noupdate /Block1_vlg_tst/i1/b2v_inst/alternate_strobe
add wave -noupdate /Block1_vlg_tst/i1/b2v_inst/EOP
add wave -noupdate /Block1_vlg_tst/i1/b2v_inst/rdata
add wave -noupdate /Block1_vlg_tst/i1/b2v_inst/rdata_ready
add wave -noupdate /Block1_vlg_tst/i1/b2v_inst/strobe
add wave -noupdate /Block1_vlg_tst/i1/b2v_inst/SOP
add wave -noupdate /Block1_vlg_tst/i1/b2v_inst/dnrzi
add wave -noupdate /Block1_vlg_tst/i1/b2v_inst/clk_counter
add wave -noupdate /Block1_vlg_tst/i1/b2v_inst/EOP_counter
add wave -noupdate /Block1_vlg_tst/i1/b2v_inst/byteready_counter
add wave -noupdate /Block1_vlg_tst/i1/b2v_inst/dpw
add wave -noupdate /Block1_vlg_tst/i1/b2v_inst/dmw
add wave -noupdate /Block1_vlg_tst/i1/b2v_inst/dp_input
add wave -noupdate /Block1_vlg_tst/i1/b2v_inst/dm_input
add wave -noupdate /Block1_vlg_tst/i1/b2v_inst/delnrzi
add wave -noupdate /Block1_vlg_tst/i1/b2v_inst/EOP_condition
add wave -noupdate /Block1_vlg_tst/i1/b2v_inst/dp_change
add wave -noupdate /Block1_vlg_tst/i1/b2v_inst/delnrziw
add wave -noupdate /Block1_vlg_tst/i1/b2v_inst/outnrzi
add wave -noupdate /Block1_vlg_tst/i1/b2v_inst1/areset
add wave -noupdate /Block1_vlg_tst/i1/b2v_inst1/inclk0
add wave -noupdate /Block1_vlg_tst/i1/b2v_inst1/c0
add wave -noupdate /Block1_vlg_tst/i1/b2v_inst1/c1
add wave -noupdate /Block1_vlg_tst/i1/b2v_inst2/clk
add wave -noupdate /Block1_vlg_tst/i1/b2v_inst2/EOP
add wave -noupdate /Block1_vlg_tst/i1/b2v_inst2/rdata
add wave -noupdate /Block1_vlg_tst/i1/b2v_inst2/rdata_ready
add wave -noupdate /Block1_vlg_tst/i1/b2v_inst2/strobe
add wave -noupdate /Block1_vlg_tst/i1/b2v_inst2/SOP
add wave -noupdate /Block1_vlg_tst/i1/b2v_inst2/strobe_sender
add wave -noupdate /Block1_vlg_tst/i1/b2v_inst2/sixone_signal
add wave -noupdate /Block1_vlg_tst/i1/b2v_inst2/SETUP_token
add wave -noupdate /Block1_vlg_tst/i1/b2v_inst2/send_reg
add wave -noupdate /Block1_vlg_tst/i1/b2v_inst2/sEOP
add wave -noupdate /Block1_vlg_tst/i1/b2v_inst2/sdata_ready
add wave -noupdate /Block1_vlg_tst/i1/b2v_inst2/btrdcnt_strobe
add wave -noupdate /Block1_vlg_tst/i1/b2v_inst2/TX_byte_CRC
add wave -noupdate /Block1_vlg_tst/i1/b2v_inst2/RX_byte
add wave -noupdate /Block1_vlg_tst/i1/b2v_inst2/TX_EN
add wave -noupdate /Block1_vlg_tst/i1/b2v_inst2/RX_DONE
add wave -noupdate /Block1_vlg_tst/i1/b2v_inst2/state
add wave -noupdate /Block1_vlg_tst/i1/b2v_inst2/bytenum
add wave -noupdate /Block1_vlg_tst/i1/b2v_inst2/PID_decoder
add wave -noupdate /Block1_vlg_tst/i1/b2v_inst2/byteready_counter
add wave -noupdate /Block1_vlg_tst/i1/b2v_inst2/ADDR_ENDP_CRC_decoder
add wave -noupdate /Block1_vlg_tst/i1/b2v_inst2/FRAMENUM_CRC_decoder
add wave -noupdate /Block1_vlg_tst/i1/b2v_inst2/bmRequestType
add wave -noupdate /Block1_vlg_tst/i1/b2v_inst2/bRequestCode
add wave -noupdate /Block1_vlg_tst/i1/b2v_inst2/wValue
add wave -noupdate /Block1_vlg_tst/i1/b2v_inst2/wIndex
add wave -noupdate /Block1_vlg_tst/i1/b2v_inst2/wLength
add wave -noupdate /Block1_vlg_tst/i1/b2v_inst2/FIFO_pointer
add wave -noupdate /Block1_vlg_tst/i1/b2v_inst2/device_address
add wave -noupdate /Block1_vlg_tst/i1/b2v_inst2/transac_counter
add wave -noupdate /Block1_vlg_tst/i1/b2v_inst2/EOP_delay
add wave -noupdate /Block1_vlg_tst/i1/b2v_inst2/xsEOP
add wave -noupdate /Block1_vlg_tst/i1/b2v_inst2/fsm_sync
add wave -noupdate /Block1_vlg_tst/i1/b2v_inst2/RX_SEND_USB
add wave -noupdate /Block1_vlg_tst/i1/b2v_inst2/SEOP
add wave -noupdate /Block1_vlg_tst/i1/b2v_inst3/uart_clk
add wave -noupdate /Block1_vlg_tst/i1/b2v_inst3/rbyteready
add wave -noupdate /Block1_vlg_tst/i1/b2v_inst3/EOP
add wave -noupdate /Block1_vlg_tst/i1/b2v_inst3/uart_tx_byte
add wave -noupdate /Block1_vlg_tst/i1/b2v_inst3/uart_rx_byte
add wave -noupdate /Block1_vlg_tst/i1/b2v_inst3/uart_tx_com1
add wave -noupdate /Block1_vlg_tst/i1/b2v_inst3/uart_rx_com1
add wave -noupdate /Block1_vlg_tst/i1/b2v_inst3/uart_tx_en
add wave -noupdate /Block1_vlg_tst/i1/b2v_inst3/usb_clk
add wave -noupdate /Block1_vlg_tst/i1/b2v_inst3/uart_tx_com2
add wave -noupdate /Block1_vlg_tst/i1/b2v_inst3/uart_rx_done
add wave -noupdate /Block1_vlg_tst/i1/b2v_inst3/uart_rx_com2
add wave -noupdate /Block1_vlg_tst/i1/b2v_inst3/tx_QUEUE_core_pointer
add wave -noupdate /Block1_vlg_tst/i1/b2v_inst3/tx_QUEUE_uart_pointer
add wave -noupdate /Block1_vlg_tst/i1/b2v_inst3/tx_QUEUE_core_last_val
add wave -noupdate /Block1_vlg_tst/i1/b2v_inst3/TX_buffer
add wave -noupdate /Block1_vlg_tst/i1/b2v_inst3/TX_shift
add wave -noupdate /Block1_vlg_tst/i1/b2v_inst3/RX_buffer
add wave -noupdate /Block1_vlg_tst/i1/b2v_inst3/RX_shift
add wave -noupdate /Block1_vlg_tst/i1/b2v_inst3/tx_data_ready
add wave -noupdate /Block1_vlg_tst/i1/b2v_inst3/tx_data_ready_counter
add wave -noupdate /Block1_vlg_tst/i1/b2v_inst3/rx_data_ready
add wave -noupdate /Block1_vlg_tst/i1/b2v_inst3/rx_data_ready_counter
add wave -noupdate /Block1_vlg_tst/i1/b2v_inst3/uart_tx
add wave -noupdate /Block1_vlg_tst/i1/b2v_inst3/uart_rx
add wave -noupdate /Block1_vlg_tst/i1/b2v_inst3/is_command_counter
add wave -noupdate /Block1_vlg_tst/i1/b2v_inst3/is_command
add wave -noupdate /Block1_vlg_tst/i1/b2v_inst3/com_port_number
add wave -noupdate /Block1_vlg_tst/i1/b2v_inst3/tx_QUEUE_pointer
add wave -noupdate /Block1_vlg_tst/i1/b2v_inst7/clk
add wave -noupdate /Block1_vlg_tst/i1/b2v_inst7/EOP
add wave -noupdate /Block1_vlg_tst/i1/b2v_inst7/rdata
add wave -noupdate /Block1_vlg_tst/i1/b2v_inst7/rdata_ready
add wave -noupdate /Block1_vlg_tst/i1/b2v_inst7/rbyte_cnt
add wave -noupdate /Block1_vlg_tst/i1/b2v_inst7/core_strobe
add wave -noupdate /Block1_vlg_tst/i1/b2v_inst7/SOP
add wave -noupdate /Block1_vlg_tst/i1/b2v_inst7/send_reg
add wave -noupdate /Block1_vlg_tst/i1/b2v_inst7/sEOP
add wave -noupdate /Block1_vlg_tst/i1/b2v_inst7/sdata_ready
add wave -noupdate /Block1_vlg_tst/i1/b2v_inst7/dp_out
add wave -noupdate /Block1_vlg_tst/i1/b2v_inst7/dm_out
add wave -noupdate /Block1_vlg_tst/i1/b2v_inst7/strobe
add wave -noupdate /Block1_vlg_tst/i1/b2v_inst7/d_out_enable
add wave -noupdate /Block1_vlg_tst/i1/b2v_inst7/sixone_signal
add wave -noupdate /Block1_vlg_tst/i1/b2v_inst7/sEOP_delay
add wave -noupdate /Block1_vlg_tst/i1/b2v_inst7/out
add wave -noupdate /Block1_vlg_tst/i1/b2v_inst7/clk_counter
add wave -noupdate /Block1_vlg_tst/i1/b2v_inst7/serial_shift
add wave -noupdate /Block1_vlg_tst/i1/b2v_inst7/NRZI_coding
add wave -noupdate /Block1_vlg_tst/i1/b2v_inst7/out_enable
add wave -noupdate /Block1_vlg_tst/i1/b2v_inst7/sixone_counter
add wave -noupdate /Block1_vlg_tst/i1/b2v_inst7/do_bitstaff
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {5050 ns} 0}
quietly wave cursor active 1
configure wave -namecolwidth 417
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {52210 ns} {58530 ns}
